from datetime import datetime

def generate_markdown_report(telemetry: dict, plan: dict, battery: dict) -> str:
    """Generates an executive technical energy audit report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report = f"""# 🌞 SolarSathi AI — Microgrid Energy & Health Audit Report
**Generated On:** {now}  
**System Status:** {plan.get('safety_status', 'Safe').upper()}  
**Battery SOH Category:** {battery.get('status', 'Unknown')} ({battery.get('health_score')}%)

---

## 1. Operating Telemetry Summary
- **Solar PV Generation:** {telemetry.get('pv_generation_kw')} kW
- **Customer Demand:** {telemetry.get('load_demand_kw')} kW
- **Battery Storage:** {telemetry.get('battery_soc')}% SOC | Capacity: {telemetry.get('battery_capacity_kwh')} kWh
- **Battery Temperature:** {telemetry.get('battery_temp_c')} °C
- **Cell Internal Resistance:** {telemetry.get('battery_internal_res_mohm')} mΩ
- **Utility Grid Status:** {'Online' if telemetry.get('grid_available') else 'Offline (Outage)'}
- **Transformer Loading:** {telemetry.get('transformer_loading_pct')}%

---

## 2. Supervisor Autonomous Energy Plan
| Asset | Commanded Action | Power Flow Allocation |
| :--- | :--- | :--- |
| **Solar PV** | {plan.get('solar_action')} | To Load: {plan['power_flows'].get('solar_to_load')} kW, To Batt: {plan['power_flows'].get('solar_to_battery')} kW |
| **Battery Storage**| {plan.get('battery_action')} | To Load: {plan['power_flows'].get('battery_to_load')} kW |
| **Utility Grid** | {plan.get('grid_action')} | To Load: {plan['power_flows'].get('grid_to_load')} kW, Export: {plan['power_flows'].get('solar_to_grid')} kW |
| **EV Charger** | {plan.get('ev_action')} | Controlled by Transformer Safety Guardrail |

---

## 3. Battery Health Doctor Diagnostic
- **State of Health (SOH) Score:** {battery.get('health_score')}/100
- **Capacity Retention:** {battery.get('capacity_retention_pct')}%
- **Identified Concerns:**
{chr(10).join(['  * ' + c for c in battery.get('observed_concerns', [])])}
- **Root-Cause Analysis:**
{chr(10).join(['  * ' + c for c in battery.get('possible_causes', [])])}
- **Technician Recommended Actions:**
{chr(10).join(['  * ' + c for c in battery.get('recommended_checks', [])])}
- **Prescribed Operating Rule:** {battery.get('recommended_operating_behavior')}

---

## 4. Engineering Guardrail Verifications
- **Replanning Iteration Triggered:** {plan.get('replanned_iteration')}
- **Active Safety Alerts:**
{chr(10).join(['  * ' + w for w in plan.get('warning_alerts', ['None. Operating within safe IEEE/NEPRA limits.'])])}

---
*Report autonomously generated by SolarSathi AI Multi-Agent Decision Engine.*
"""
    return report
